# Project
version=11.0.0
group=com.grim3212.assorted.tools
license=LGPL-3.0-only
issue_tracker=https://github.com/grim3212/AssortedTools/issues
# Common
minecraft_version=26.2
minecraft_version_range=[26.2]
neoform_version=26.2-2
moddev_version=2.0.146
mixin_version=0.8.7
common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server
# NeoForge
neoforge_version=26.2.0.82
neoforge_version_range=[26.2.0.82,)
neoforge_ats_enabled=false
# Fabric
fabric_version=0.160.0+26.2
fabric_mc_version_range=26.2
fabric_loader_version=0.19.5
loom_version=1.17-SNAPSHOT
# Mod Options
mod_name=Assorted Tools
mod_author=Grim3212
mod_id=assortedtools
mod_description=An assortment of tools and armor.
# Assorted lib version to use
assortedlib_version=4.0.0
# Dependencies
jei_minecraft_version=26.2
jei_version=30.32.0.209
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false
