# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml"
loaderVersion="[38,)"
license="GPL-3.0 License"
issueTrackerURL="https://github.com/grim3212/AssortedTools"

[[mods]]
modId="assortedtools"
version="${file.jarVersion}"
displayName="Assorted Tools"
#updateJSONURL=""
displayURL="https://assortedmods.com/tools"
logoFile="logo.png"
authors="Grim3212"
description='''
An assortment of various helpful tools to add to your Minecraft world.
'''

[[dependencies.assortedtools]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.assortedtools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18]"
    ordering="NONE"
    side="BOTH"
